Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/back-office/info/urls.py
from django.urls import path
from .views import InfoListView, InfoDetailView, InfoCreateView, InfoUpdateView, InfoDeleteView


urlpatterns = [
    path('info/', InfoListView.as_view(), name='info_list'),
    path('detail/<int:pk>/', InfoDetailView.as_view(), name='info_detail'),
    path('create/', InfoCreateView.as_view(), name='info_create'),
    path('update/<int:pk>', InfoUpdateView.as_view(), name='info_update'),
    path('delete/<int:pk>/', InfoDeleteView.as_view(), name='info_delete'),
]

dashboard/back-office/urls.py
from django.urls import path, include

urlpatterns = [
    path('banners/', include('dashboard.back-office.banners.urls')),
    path('service/', include('dashboard.back-office.service.urls')),
    path('contact/', include('dashboard.back-office.contact.urls')),
    path('info/', include('dashboard.back-office.info.urls')),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

main/models.py
from django.db import models


class Banner(models.Model):
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='banners/')
    created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    
class Service(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='services/')
    created = models.DateTimeField(auto_now_add=True)
    img_label = models.CharField(max_length=255)

    def __str__(self):
        return self.title
    
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=13)
    message = models.TextField()    

    def __str__(self):
        return self.name
    
    
class Info(models.Model):
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

    
    

    

dashboard/back-office/banners/forms.py
from django import forms
from main.models import Banner

class BannerForm(forms.ModelForm):
    class Meta:
        model = Banner
        fields = ['title', 'sub_title', 'image', 'is_active']

dashboard/back-office/contact/forms.py
from django import forms
from main.models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'message']

dashboard/back-office/info/forms.py
from django import forms
from main.models import Info

class InfoForm(forms.ModelForm):
    class Meta:
        model = Info
        fields = ['address', 'phone', 'email']

dashboard/back-office/service/forms.py
from django import forms
from main.models import Service

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['title', 'description', 'image', 'img_label']

dashboard/back-office/banners/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from main.models import Banner
from . import forms


class BannerListView(ListView):
    model = Banner
    template_name = 'dashboard/back-office/banners/banner_list.html'
    context_object_name = 'banners'

class BannerCreateView(CreateView):
    model = Banner
    form_class = forms.BannerForm
    template_name = 'dashboard/back-office/banners/banner_update.html'
    success_url = reverse_lazy('banner_list')

class BannerUpdateView(UpdateView):
    model = Banner
    form_class = forms.BannerForm
    template_name = 'dashboard/back-office/banners/banner_update.html'
    success_url = reverse_lazy('banner_list')

class BannerDeleteView(DeleteView):
    model = Banner
    template_name = 'dashboard/back-office/banners/banner_delete.html'
    success_url = reverse_lazy('banner_list')

dashboard/back-office/contact/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from main.models import Contact
from .forms import ContactForm

class ContactListView(ListView):
    model = Contact
    template_name = 'dashboard/back-office/contact/contact_list.html'
    context_object_name = 'contacts'

class ContactDetailView(DetailView):
    model = Contact
    template_name = 'dashboard/back-office/contact/contact_detail.html'

class ContactCreateView(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'dashboard/back-office/contact/contact_update.html'
    success_url = reverse_lazy('contact_list')
    extra_context = {'form_title': 'Add New Contact'}

class ContactUpdateView(UpdateView):
    model = Contact
    form_class = ContactForm
    template_name = 'dashboard/back-office/contact/contact_update.html'
    success_url = reverse_lazy('contact_list')
    extra_context = {'form_title': 'Edit Contact'}

class ContactDeleteView(DeleteView):
    model = Contact
    template_name = 'dashboard/back-office/contact/contact_delete.html'
    success_url = reverse_lazy('contact_list')

dashboard/back-office/info/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from main.models import Info
from .forms import InfoForm

class InfoListView(ListView):
    model = Info
    template_name = 'dashboard/back-office/info/info_list.html'
    context_object_name = 'infos'

class InfoDetailView(DetailView):
    model = Info
    template_name = 'dashboard/back-office/info/info_detail.html'

class InfoCreateView(CreateView):
    model = Info
    form_class = InfoForm
    template_name = 'dashboard/back-office/info/info_update.html'
    success_url = reverse_lazy('info_list')
    extra_context = {'form_title': 'Add New Info'}

class InfoUpdateView(UpdateView):
    model = Info
    form_class = InfoForm
    template_name = 'dashboard/back-office/info/info_update.html'
    success_url = reverse_lazy('info_list')
    extra_context = {'form_title': 'Edit Info'}

class InfoDeleteView(DeleteView):
    model = Info
    template_name = 'dashboard/back-office/info/info_delete.html'
    success_url = reverse_lazy('info_list')

dashboard/back-office/service/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from main.models import Service
from .forms import ServiceForm


class ServiceListView(ListView):
    model = Service
    template_name = 'dashboard/back-office/service/service_list.html'
    context_object_name = 'services'

class ServiceDetailView(DetailView):
    model = Service
    template_name = 'dashboard/back-office/service/service_detail.html'
    context_object_name = 'service'


class ServiceCreateView(CreateView):
    model = Service
    form_class = ServiceForm
    template_name = 'dashboard/back-office/service/service_create.html'
    success_url = reverse_lazy('service_list')


class ServiceUpdateView(UpdateView):
    model = Service
    form_class = ServiceForm
    template_name = 'dashboard/back-office/service/service_update.html'
    success_url = reverse_lazy('service_list')


class ServiceDeleteView(DeleteView):
    model = Service
    template_name = 'dashboard/back-office/service/service_delete.html'
    success_url = reverse_lazy('service_list')

templates/dashboard/back-office/banners/banner_delete.html
{% extends 'dashboard/base.html' %}
{% block content %}

<div class="container mt-4">
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Delete Banner</h4>
        <p class="mb-0">Are you sure you want to delete <strong>"{{ object.title }}"</strong>?</p>
    </div>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-danger">Yes, delete</button>
            <a href="{% url 'banner_list' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

templates/dashboard/back-office/banners/banner_list.html
{% extends 'dashboard/base.html' %}
{% block content %}

<div class="container mt-4">
    <h1 class="mb-4">Banner List</h1>
    <a href="{% url 'banner_create' %}" class="btn btn-primary mb-3">Create New Banner</a>

    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Sub Title</th>
                <th scope="col">Image</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for banner in banners %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ banner.title }}</td>
                    <td>{{ banner.sub_title }}</td>
                    <td>
                        {% if banner.image %}
                            <img src="{{ banner.image.url }}" alt="{{ banner.title }}" class="img-thumbnail" style="max-width: 100px;">
                        {% else %}
                            No Image
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'banner_update' banner.pk %}" class="btn btn-sm btn-warning">Update</a>
                        <a href="{% url 'banner_delete' banner.pk %}" class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/dashboard/back-office/banners/banner_update.html
{% extends 'dashboard/base.html' %}
{% block content %}

<div class="container mt-4">
    <h1 class="mb-4">{% if object %}Update Banner{% else %}Create Banner{% endif %}</h1>

    <form method="post" enctype="multipart/form-data" class="bg-light p-4 rounded shadow-sm">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="id_title">Title</label>
                {{ form.title }}
            </div>
            <div class="form-group col-md-4">
                <label for="id_sub_title">Sub Title</label>
                {{ form.sub_title }}
            </div>
            <div class="form-group col-md-4">
                <label for="id_image">Image</label>
                {{ form.image }}
            </div>
        </div>
        <div class="form-check form-check-inline">
            {{ form.is_active }} <label for="id_is_active" class="form-check-label">Active</label>
        </div>
        <div class="form-group mt-3">
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{% url 'banner_list' %}" class="btn btn-secondary">Back to List</a>
        </div>
    </form>
</div>

{% endblock %}